openapi: 3.0.2

info:
  version: "${project.version}"
  title: "${project.name}"
  description: |
    ${project.description}
  contact:
    email: "${user.name}@kb.dk"
  license:
    name: "${license.name}"
    url: "${license.url}"

servers:
  #  /api must match servlet-mapping in web.xml
  - url: "/${project.artifactId}/api"
    description: "Current server"

paths:
  /newspaperIDs:
    get:
      operationId: getNewspaperIDs
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /batch:
    get:
      operationId: getBatches
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Batch"



  /batch/{batchID}:
    get:
      operationId: getBatch
      parameters:
        - name: batchID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Batch"


  /batch/{batchID}/{year}:
    get:
      operationId: getBatchDatesForNewspaper
      parameters:
        - name: batchID
          in: path
          required: true
          schema:
            type: string
        - name: year
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewspaperDate'

  /batch/{batchID}/{newspaperID}/{date}:
    get:
      operationId: getMappedEntititesForNewspaperDate
      parameters:
        - name: batchID
          in: path
          required: true
          schema:
            type: string
        - name: newspaperID
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewspaperDay'


  /years/{newspaperID}:
    get:
      operationId: getYearsForNewspaper
      parameters:
        - name: newspaperID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string


  /dates/{newspaperID}/{year}:
    get:
      operationId: getDatesForNewspaperYear
      parameters:
        - name: newspaperID
          in: path
          required: true
          schema:
            type: string
        - name: year
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewspaperDate'





  /entity/{handle}/url/{type}:
    get:
      operationId: getEntityURL
      parameters:
        - name: handle
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: string
                format: uri

  /entity/{handle}/characterization}:
    get:
      operationId: getEntityCharacterization
      parameters:
        - name: handle
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterizationInfo'


  /notes/{batchID}:
    post:
      operationId: setNotes
      summary: ""
      parameters:
        - name: batchID
          in: path
          required: true
          schema:
            type: string
        - name: avis
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: true
          schema:
            type: string
        #            format: date
        - name: edition
          in: query
          required: false
          schema:
            type: string
        - name: section
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: string

      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        #        TODO here
        '201':
          description: Created

components:
  schemas:

    Batch:
      type: object
      properties:
        batchid:
          type: string
        avisid:
          type: string
        roundtrip:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        deliveryDate:
          type: string
          format: date
        problems:
          description: "Problems not associated with any page"
          type: string
          nullable: true
        numProblems:
          description: "Number of problems found. Use this to see if the batch completed checks without any errors"
          type: integer
        notes:
          type: string
          nullable: true
        state:
          type: string

    NewspaperDate:
      type: object
      properties:
        batchid:
          type: string
        avisid:
          type: string
        roundtrip:
          type: integer
        date:
          type: string
          format: date
        pageCount:
          type: integer
        editionCount:
          type: integer
        state:
          type: string
        problems:
          type: string

    NewspaperDay:
      type: object
      properties:
        batchid:
          type: string
        avisid:
          type: string
        date:
          type: string
          format: date
        notes:
          type: string
          nullable: true
        editions:
          type: array
          items:
            $ref: '#/components/schemas/NewspaperEdition'

    NewspaperEdition:
      type: object
      properties:
        batchid:
          type: string
        avisid:
          type: string
        date:
          type: string
          format: date
        edition:
          type: string
        notes:
          type: string
        pages:
          type: array
          items:
            $ref: '#/components/schemas/NewspaperEntity'

    NewspaperEntity:
      type: object
      properties:
        batchid:
          type: string
        origRelpath:
          type: string
        formatType:
          type: string
        editionDate:
          type: string
          format: date
        singlePage:
          type: boolean
        pageNumber:
          type: integer
        avisid:
          type: string
        avistitle:
          type: string
        shadowPath:
          type: string
        sectionTitle:
          type: string
        editionTitle:
          type: string
        deliveryDate:
          type: string
          format: date
        handle:
          type: integer
          format: int64
        fraktur:
          type: boolean
        problems:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true



    CharacterizationInfo:
      type: object
      properties:
        origRelpath:
          type: string
        tool:
          type: string
        characterisationDate:
          type: string
          format: date
        toolOutput:
          type: string
        status:
          type: string
